name: CI para API de Data e Hora

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install "fastapi[all]" uvicorn pytz
          pip install "requests[all]" # Necessário para o script de teste

      - name: Rodar o servidor da API em background
        run: |
          uvicorn main:app --host 0.0.0.0 --port 8000 &
          sleep 5

      - name: Executar testes da API
        run: |
          python test_api.py